image:
  file: .gitpod.dockerfile

#tasks:
 # - init: echo "Replace me with a build script for the project."
  #  command: echo "Replace me with omething that should run on every start, or just
   #   remove me entirely."


# these task is to create custom workspace with prebuild so that I don't have to code again n again..
tasks:
  - init: |
     export PIP_USER=no
     cd fintech_app/
     virtualenv -p python3 venv
     source venv/bin/activate
     pip install -r requirements.txt
     
  # - init: |
    #  mysql -e "create database website;"

   #   i have to continue more on this
